# Generated by Django 4.2.7 on 2023-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag_id',
            field=models.ManyToManyField(related_name='news', to='home.tag'),
        ),
    ]
