# Generated by Django 4.2.7 on 2023-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
